name: Laravel

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./src
    - name: Install Dependencies
      run: composer install 
      working-directory: ./src
    - name: Generate key
      run: php artisan key:generate
      working-directory: ./src

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./src
   
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      working-directory: ./src

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Composer build 
      runs:
      using: 'docker'
      image: './docker/composer/Dockerfile'

    - name: Build and Push to Docker Hub for Nginx 
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: araiyusuke/ecs-hands-on-nginx:latest
        file: ./docker/nginx/Dockerfile

    - name: Build and Push to Docker Hub for Laravel 
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: araiyusuke/ecs-hands-on-laravel:latest
        file: ./docker/laravel/Dockerfile
